export {
  useCreateCashDeskMutation,
  useDetectFiscalDevicesMutation,
  useCreateIntegrationConfigMutation,
  useCreatePrepStationMutation,
  useCreateRestaurantMutation,
  useDeleteCashDeskMutation,
  useDeleteIntegrationConfigMutation,
  useDeletePrepStationMutation,
  useDeleteRestaurantMutation,
  useUpdateCashDeskMutation,
  useUpdateIntegrationConfigMutation,
  useUpdateMyRestaurantSettingsMutation,
  useUpdatePrepStationMutation,
  useUpdateRestaurantMutation,
} from './mutations';
export {
  useGetCashDesksListQuery,
  useGetCashDesksQuery,
  useGetCashDeskByIdQuery,
  useGetIntegrationConfigByIdQuery,
  useGetIntegrationConfigsListQuery,
  useGetIntegrationConfigsQuery,
  useGetOrganizationsHallsQuery,
  useGetMyRestaurantQuery,
  useGetOrganizationsPrepStationByIdQuery,
  useGetPrepStationsListQuery,
  useGetPrepStationsQuery,
  useGetRestaurantByIdQuery,
  useGetRestaurantsListQuery,
  useGetRestaurantsQuery,
} from './queries';
