export {
  useCreateCashDeskMutation,
  useCreateDeviceMutation,
  useCreateDistributionPointMutation,
  useCreatePrepStationMutation,
  useCreateRestaurantMutation,
  useDeleteCashDeskMutation,
  useDeleteDeviceMutation,
  useDeleteDistributionPointMutation,
  useDeletePrepStationMutation,
  useDeleteRestaurantMutation,
  useUpdateCashDeskMutation,
  useUpdateDeviceMutation,
  useUpdateDistributionPointMutation,
  useUpdatePrepStationMutation,
  useUpdateRestaurantMutation,
} from './mutations';
export {
  useGetCashDesksListQuery,
  useGetCashDesksQuery,
  useGetCashDeskByIdQuery,
  useGetDevicesListQuery,
  useGetDevicesQuery,
  useGetDeviceByIdQuery,
  useGetDistributionPointsListQuery,
  useGetDistributionPointsQuery,
  useGetDistributionPointByIdQuery,
  useGetOrganizationsHallsQuery,
  useGetMyRestaurantQuery,
  useGetOrganizationsPrepStationByIdQuery,
  useGetPrepStationsListQuery,
  useGetPrepStationsQuery,
  useGetRestaurantByIdQuery,
  useGetRestaurantsListQuery,
  useGetRestaurantsQuery,
} from './queries';
