services:
  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-postcode-admin-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
