export const floorKeys = {
  all: ['floor'] as const,
  users: () => [...floorKeys.all, 'users'] as const,
  halls: () => [...floorKeys.all, 'halls'] as const,
  hallsList: (params: Record<string, unknown>) => [...floorKeys.halls(), 'list', params] as const,
  hallDetail: (id: string) => [...floorKeys.all, 'hall', id] as const,
  hallConstructor: (id: string) => [...floorKeys.hallDetail(id), 'constructor'] as const,
  zones: () => [...floorKeys.all, 'zones'] as const,
  zonesList: (params: Record<string, unknown>) => [...floorKeys.zones(), 'list', params] as const,
  zoneDetail: (id: string) => [...floorKeys.all, 'zone', id] as const,
  diningTables: () => [...floorKeys.all, 'diningTables'] as const,
  diningTablesList: (params: Record<string, unknown>) => [...floorKeys.diningTables(), 'list', params] as const,
  diningTableDetail: (id: string) => [...floorKeys.all, 'diningTable', id] as const,
  tableSessions: () => [...floorKeys.all, 'tableSessions'] as const,
  tableSessionsList: (params: Record<string, unknown>) => [...floorKeys.tableSessions(), 'list', params] as const,
  tableSessionDetail: (id: string) => [...floorKeys.all, 'tableSession', id] as const,
} as const;
