import { getPath } from './get-path';

export const enum AppRoutes {
  LOGIN = 'login',
  MAIN = 'main',
  USER_LIST = 'userList',
  ROLE_LIST = 'roleList',
  PERMISSION_LIST = 'permissionList',
  PLATFORM_BUSINESS_PARTNER_LIST = 'platformBusinessPartnerList',
  PLATFORM_BUSINESS_PARTNER_CREATE = 'platformBusinessPartnerCreate',
  PLATFORM_BUSINESS_PARTNER_EDIT = 'platformBusinessPartnerEdit',
  PLATFORM_TARIFF_LIST = 'platformTariffList',
  PLATFORM_TARIFF_CREATE = 'platformTariffCreate',
  PLATFORM_TARIFF_EDIT = 'platformTariffEdit',
  ORDER_LIST = 'orderList',
  ORDER_VIEW = 'orderView',
  ORDER_ITEM_LIST = 'orderItemList',
  ORDER_ITEM_VIEW = 'orderItemView',
  ORDER_ITEM_NOTE_LIST = 'orderItemNoteList',
  ORDER_ITEM_NOTE_VIEW = 'orderItemNoteView',
  PAYMENT_LIST = 'paymentList',
  PAYMENT_VIEW = 'paymentView',
  RECEIPT_LIST = 'receiptList',
  RECEIPT_VIEW = 'receiptView',
  REPORTS = 'reports',
  REPORT_DETAIL = 'reportDetail',
  KITCHEN_TICKET_LIST = 'kitchenTicketList',
  KITCHEN_TICKET_VIEW = 'kitchenTicketView',
  CATALOG_CATEGORY_LIST = 'catalogCategoryList',
  CATALOG_ITEM_LIST = 'catalogItemList',
  ORGANIZATION_BRANCH_LIST = 'organizationBranchList',
  ORGANIZATION_FEATURE_CONFIG_LIST = 'organizationFeatureConfigList',
  ORGANIZATION_MY_RESTAURANT = 'organizationMyRestaurant',
  ORGANIZATION_RESTAURANT_FEATURE_CONFIG = 'organizationRestaurantFeatureConfig',
  ORGANIZATION_RESTAURANT_LIST = 'organizationRestaurantList',
  FLOOR_HALL_LIST = 'floorHallList',
  FLOOR_HALL_CONSTRUCTOR = 'floorHallConstructor',
  FLOOR_ZONE_LIST = 'floorZoneList',
  FLOOR_LAYOUT_OBJECT_LIST = 'floorLayoutObjectList',
  FLOOR_LAYOUT_TEMPLATE_LIST = 'floorLayoutTemplateList',
  FLOOR_TABLE_SESSION_LIST = 'floorTableSessionList',
  USER_CREATE = 'userCreate',
  ROLE_CREATE = 'roleCreate',
  ROLE_EDIT = 'roleEdit',
  USER_EDIT = 'userEdit',
  USER_VIEW = 'userView',
  CATALOG_CATEGORY_CREATE = 'catalogCategoryCreate',
  CATALOG_CATEGORY_EDIT = 'catalogCategoryEdit',
  CATALOG_ITEM_CREATE = 'catalogItemCreate',
  CATALOG_ITEM_EDIT = 'catalogItemEdit',
  ORGANIZATION_BRANCH_CREATE = 'organizationBranchCreate',
  ORGANIZATION_BRANCH_EDIT = 'organizationBranchEdit',
  ORGANIZATION_FEATURE_CONFIG_CREATE = 'organizationFeatureConfigCreate',
  ORGANIZATION_FEATURE_CONFIG_EDIT = 'organizationFeatureConfigEdit',
  ORGANIZATION_RESTAURANT_CREATE = 'organizationRestaurantCreate',
  ORGANIZATION_RESTAURANT_EDIT = 'organizationRestaurantEdit',
  FLOOR_HALL_CREATE = 'floorHallCreate',
  FLOOR_HALL_EDIT = 'floorHallEdit',
  FLOOR_ZONE_CREATE = 'floorZoneCreate',
  FLOOR_ZONE_EDIT = 'floorZoneEdit',
  FLOOR_LAYOUT_OBJECT_CREATE = 'floorLayoutObjectCreate',
  FLOOR_LAYOUT_OBJECT_EDIT = 'floorLayoutObjectEdit',
  FLOOR_LAYOUT_TEMPLATE_CREATE = 'floorLayoutTemplateCreate',
  FLOOR_LAYOUT_TEMPLATE_EDIT = 'floorLayoutTemplateEdit',
  FLOOR_TABLE_SESSION_CREATE = 'floorTableSessionCreate',
  FLOOR_TABLE_SESSION_EDIT = 'floorTableSessionEdit',
  NOTFOUND = 'notfound',
}

export const enum AppRoutesRoot {
  AUTH = 'auth',
  MAIN = 'main',
  USERS = 'users',
  ROLES = 'roles',
  PERMISSIONS = 'permissions',
  PLATFORM = 'platform',
  ORDERS = 'orders',
  ORDER_ITEMS = 'order-items',
  ORDER_ITEM_NOTES = 'order-item-notes',
  PAYMENTS = 'payments',
  RECEIPTS = 'receipts',
  REPORTS = 'reports',
  KITCHEN = 'kitchen',
  CATALOG = 'catalog',
  ORGANIZATIONS = 'organizations',
  FLOOR = 'floor',
  ERROR = 'error',
}

export const RouteRootPath: Record<AppRoutesRoot, string> = {
  [AppRoutesRoot.MAIN]: '/',
  [AppRoutesRoot.AUTH]: '/auth',
  [AppRoutesRoot.USERS]: '/users',
  [AppRoutesRoot.ROLES]: '/roles',
  [AppRoutesRoot.PERMISSIONS]: '/permissions',
  [AppRoutesRoot.PLATFORM]: '/platform',
  [AppRoutesRoot.ORDERS]: '/orders',
  [AppRoutesRoot.ORDER_ITEMS]: '/order-items',
  [AppRoutesRoot.ORDER_ITEM_NOTES]: '/order-item-notes',
  [AppRoutesRoot.PAYMENTS]: '/payments',
  [AppRoutesRoot.RECEIPTS]: '/receipts',
  [AppRoutesRoot.REPORTS]: '/reports',
  [AppRoutesRoot.KITCHEN]: '/kitchen',
  [AppRoutesRoot.CATALOG]: '/catalog',
  [AppRoutesRoot.ORGANIZATIONS]: '/organizations',
  [AppRoutesRoot.FLOOR]: '/floor',
  [AppRoutesRoot.ERROR]: '/error',
};

export const RoutePath: Record<AppRoutes, string> = {
  [AppRoutes.LOGIN]: `${RouteRootPath[AppRoutesRoot.AUTH]}/login`,
  [AppRoutes.MAIN]: RouteRootPath[AppRoutesRoot.MAIN],
  [AppRoutes.USER_LIST]: RouteRootPath[AppRoutesRoot.USERS],
  [AppRoutes.ROLE_LIST]: RouteRootPath[AppRoutesRoot.ROLES],
  [AppRoutes.PERMISSION_LIST]: RouteRootPath[AppRoutesRoot.PERMISSIONS],
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_LIST]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/business-partners`,
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_CREATE]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/business-partners/add`,
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_EDIT]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/business-partners/:id/edit`,
  [AppRoutes.PLATFORM_TARIFF_LIST]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/tariffs`,
  [AppRoutes.PLATFORM_TARIFF_CREATE]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/tariffs/add`,
  [AppRoutes.PLATFORM_TARIFF_EDIT]: `${RouteRootPath[AppRoutesRoot.PLATFORM]}/tariffs/:id/edit`,
  [AppRoutes.ORDER_LIST]: RouteRootPath[AppRoutesRoot.ORDERS],
  [AppRoutes.ORDER_VIEW]: `${RouteRootPath[AppRoutesRoot.ORDERS]}/:id`,
  [AppRoutes.ORDER_ITEM_LIST]: RouteRootPath[AppRoutesRoot.ORDER_ITEMS],
  [AppRoutes.ORDER_ITEM_VIEW]: `${RouteRootPath[AppRoutesRoot.ORDER_ITEMS]}/:id`,
  [AppRoutes.ORDER_ITEM_NOTE_LIST]: RouteRootPath[AppRoutesRoot.ORDER_ITEM_NOTES],
  [AppRoutes.ORDER_ITEM_NOTE_VIEW]: `${RouteRootPath[AppRoutesRoot.ORDER_ITEM_NOTES]}/:id`,
  [AppRoutes.PAYMENT_LIST]: RouteRootPath[AppRoutesRoot.PAYMENTS],
  [AppRoutes.PAYMENT_VIEW]: `${RouteRootPath[AppRoutesRoot.PAYMENTS]}/:id`,
  [AppRoutes.RECEIPT_LIST]: RouteRootPath[AppRoutesRoot.RECEIPTS],
  [AppRoutes.RECEIPT_VIEW]: `${RouteRootPath[AppRoutesRoot.RECEIPTS]}/:id`,
  [AppRoutes.REPORTS]: RouteRootPath[AppRoutesRoot.REPORTS],
  [AppRoutes.REPORT_DETAIL]: `${RouteRootPath[AppRoutesRoot.REPORTS]}/:reportKey`,
  [AppRoutes.KITCHEN_TICKET_LIST]: `${RouteRootPath[AppRoutesRoot.KITCHEN]}/tickets`,
  [AppRoutes.KITCHEN_TICKET_VIEW]: `${RouteRootPath[AppRoutesRoot.KITCHEN]}/tickets/:id`,
  [AppRoutes.CATALOG_CATEGORY_LIST]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/categories`,
  [AppRoutes.CATALOG_ITEM_LIST]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/items`,
  [AppRoutes.ORGANIZATION_BRANCH_LIST]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/branches`,
  [AppRoutes.ORGANIZATION_FEATURE_CONFIG_LIST]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/feature-configs`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/my-restaurant`,
  [AppRoutes.ORGANIZATION_RESTAURANT_FEATURE_CONFIG]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/restaurants/:restaurantId/feature-config`,
  [AppRoutes.ORGANIZATION_RESTAURANT_LIST]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/restaurants`,
  [AppRoutes.FLOOR_HALL_LIST]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/halls`,
  [AppRoutes.FLOOR_HALL_CONSTRUCTOR]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/halls/:id/constructor`,
  [AppRoutes.FLOOR_ZONE_LIST]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/zones`,
  [AppRoutes.FLOOR_LAYOUT_OBJECT_LIST]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-objects`,
  [AppRoutes.FLOOR_LAYOUT_TEMPLATE_LIST]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-templates`,
  [AppRoutes.FLOOR_TABLE_SESSION_LIST]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/table-sessions`,
  [AppRoutes.USER_CREATE]: `${RouteRootPath[AppRoutesRoot.USERS]}/add`,
  [AppRoutes.ROLE_CREATE]: `${RouteRootPath[AppRoutesRoot.ROLES]}/add`,
  [AppRoutes.ROLE_EDIT]: `${RouteRootPath[AppRoutesRoot.ROLES]}/:id/edit`,
  [AppRoutes.USER_EDIT]: `${RouteRootPath[AppRoutesRoot.USERS]}/:id/edit`,
  [AppRoutes.USER_VIEW]: `${RouteRootPath[AppRoutesRoot.USERS]}/:id`,
  [AppRoutes.CATALOG_CATEGORY_CREATE]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/categories/add`,
  [AppRoutes.CATALOG_CATEGORY_EDIT]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/categories/:id/edit`,
  [AppRoutes.CATALOG_ITEM_CREATE]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/items/add`,
  [AppRoutes.CATALOG_ITEM_EDIT]: `${RouteRootPath[AppRoutesRoot.CATALOG]}/items/:id/edit`,
  [AppRoutes.ORGANIZATION_BRANCH_CREATE]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/branches/add`,
  [AppRoutes.ORGANIZATION_BRANCH_EDIT]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/branches/:id/edit`,
  [AppRoutes.ORGANIZATION_FEATURE_CONFIG_CREATE]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/feature-configs/add`,
  [AppRoutes.ORGANIZATION_FEATURE_CONFIG_EDIT]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/feature-configs/:id/edit`,
  [AppRoutes.ORGANIZATION_RESTAURANT_CREATE]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/restaurants/add`,
  [AppRoutes.ORGANIZATION_RESTAURANT_EDIT]: `${RouteRootPath[AppRoutesRoot.ORGANIZATIONS]}/restaurants/:id/edit`,
  [AppRoutes.FLOOR_HALL_CREATE]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/halls/add`,
  [AppRoutes.FLOOR_HALL_EDIT]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/halls/:id/edit`,
  [AppRoutes.FLOOR_ZONE_CREATE]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/zones/add`,
  [AppRoutes.FLOOR_ZONE_EDIT]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/zones/:id/edit`,
  [AppRoutes.FLOOR_LAYOUT_OBJECT_CREATE]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-objects/add`,
  [AppRoutes.FLOOR_LAYOUT_OBJECT_EDIT]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-objects/:id/edit`,
  [AppRoutes.FLOOR_LAYOUT_TEMPLATE_CREATE]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-templates/add`,
  [AppRoutes.FLOOR_LAYOUT_TEMPLATE_EDIT]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/layout-templates/:id/edit`,
  [AppRoutes.FLOOR_TABLE_SESSION_CREATE]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/table-sessions/add`,
  [AppRoutes.FLOOR_TABLE_SESSION_EDIT]: `${RouteRootPath[AppRoutesRoot.FLOOR]}/table-sessions/:id/edit`,
  [AppRoutes.NOTFOUND]: '*',
} as const;

export const RouterPathHelper = {
  platformBusinessPartnerEdit: (id: string) => getPath(AppRoutes.PLATFORM_BUSINESS_PARTNER_EDIT, { id }),
  platformTariffEdit: (id: string) => getPath(AppRoutes.PLATFORM_TARIFF_EDIT, { id }),
  userView: (id: string) => getPath(AppRoutes.USER_VIEW, { id }),
  orderView: (id: string) => getPath(AppRoutes.ORDER_VIEW, { id }),
  orderItemView: (id: string) => getPath(AppRoutes.ORDER_ITEM_VIEW, { id }),
  orderItemNoteView: (id: string) => getPath(AppRoutes.ORDER_ITEM_NOTE_VIEW, { id }),
  paymentView: (id: string) => getPath(AppRoutes.PAYMENT_VIEW, { id }),
  receiptView: (id: string) => getPath(AppRoutes.RECEIPT_VIEW, { id }),
  reportDetail: (reportKey: string) => getPath(AppRoutes.REPORT_DETAIL, { reportKey }),
  kitchenTicketView: (id: string) => getPath(AppRoutes.KITCHEN_TICKET_VIEW, { id }),
  userEdit: (id: string) => getPath(AppRoutes.USER_EDIT, { id }),
  roleEdit: (id: string) => getPath(AppRoutes.ROLE_EDIT, { id }),
  catalogCategoryEdit: (id: string) => getPath(AppRoutes.CATALOG_CATEGORY_EDIT, { id }),
  catalogItemEdit: (id: string) => getPath(AppRoutes.CATALOG_ITEM_EDIT, { id }),
  organizationBranchEdit: (id: string) => getPath(AppRoutes.ORGANIZATION_BRANCH_EDIT, { id }),
  organizationFeatureConfigEdit: (id: string) => getPath(AppRoutes.ORGANIZATION_FEATURE_CONFIG_EDIT, { id }),
  organizationRestaurantFeatureConfig: (restaurantId: string) =>
    getPath(AppRoutes.ORGANIZATION_RESTAURANT_FEATURE_CONFIG, { restaurantId }),
  organizationRestaurantEdit: (id: string) => getPath(AppRoutes.ORGANIZATION_RESTAURANT_EDIT, { id }),
  floorHallEdit: (id: string) => getPath(AppRoutes.FLOOR_HALL_EDIT, { id }),
  floorHallConstructor: (id: string) => getPath(AppRoutes.FLOOR_HALL_CONSTRUCTOR, { id }),
  floorZoneEdit: (id: string) => getPath(AppRoutes.FLOOR_ZONE_EDIT, { id }),
  floorLayoutObjectEdit: (id: string) => getPath(AppRoutes.FLOOR_LAYOUT_OBJECT_EDIT, { id }),
  floorLayoutTemplateEdit: (id: string) => getPath(AppRoutes.FLOOR_LAYOUT_TEMPLATE_EDIT, { id }),
  floorTableSessionEdit: (id: string) => getPath(AppRoutes.FLOOR_TABLE_SESSION_EDIT, { id }),
} as const;
