import { getPath } from './get-path';

export const enum AppRoutes {
  LOGIN = 'login',
  MAIN = 'main',
  USER_LIST = 'userList',
  EMPLOYEE_LIST = 'employeeList',
  ROLE_LIST = 'roleList',
  PERMISSION_LIST = 'permissionList',
  PLATFORM_BUSINESS_PARTNER_LIST = 'platformBusinessPartnerList',
  PLATFORM_BUSINESS_PARTNER_CREATE = 'platformBusinessPartnerCreate',
  PLATFORM_BUSINESS_PARTNER_EDIT = 'platformBusinessPartnerEdit',
  PLATFORM_TARIFF_LIST = 'platformTariffList',
  PLATFORM_TARIFF_CREATE = 'platformTariffCreate',
  PLATFORM_TARIFF_EDIT = 'platformTariffEdit',
  ORDER_LIST = 'orderList',
  ORDER_VIEW = 'orderView',
  ORDER_ITEM_LIST = 'orderItemList',
  ORDER_ITEM_VIEW = 'orderItemView',
  ORDER_ITEM_NOTE_LIST = 'orderItemNoteList',
  ORDER_ITEM_NOTE_VIEW = 'orderItemNoteView',
  PAYMENT_LIST = 'paymentList',
  PAYMENT_VIEW = 'paymentView',
  RECEIPT_LIST = 'receiptList',
  RECEIPT_VIEW = 'receiptView',
  REPORTS = 'reports',
  REPORT_DETAIL = 'reportDetail',
  KITCHEN_TICKET_LIST = 'kitchenTicketList',
  KITCHEN_TICKET_VIEW = 'kitchenTicketView',
  CATALOG_CATEGORY_LIST = 'catalogCategoryList',
  CATALOG_BROWSER = 'catalogBrowser',
  CATALOG_ITEM_LIST = 'catalogItemList',
  ORGANIZATION_MY_RESTAURANT = 'organizationMyRestaurant',
  ORGANIZATION_MY_RESTAURANT_GENERAL = 'organizationMyRestaurantGeneral',
  ORGANIZATION_MY_RESTAURANT_CASH_DESK_LIST = 'organizationMyRestaurantCashDeskList',
  ORGANIZATION_MY_RESTAURANT_PREP_STATION_LIST = 'organizationMyRestaurantPrepStationList',
  ORGANIZATION_MY_RESTAURANT_DISTRIBUTION_POINT_LIST = 'organizationMyRestaurantDistributionPointList',
  ORGANIZATION_MY_RESTAURANT_INTEGRATION_CONFIG_LIST = 'organizationMyRestaurantIntegrationConfigList',
  ORGANIZATION_RESTAURANT_LIST = 'organizationRestaurantList',
  FLOOR_HALL_LIST = 'floorHallList',
  FLOOR_HALL_CONSTRUCTOR = 'floorHallConstructor',
  FLOOR_ZONE_LIST = 'floorZoneList',
  FLOOR_TABLE_SESSION_LIST = 'floorTableSessionList',
  USER_CREATE = 'userCreate',
  EMPLOYEE_CREATE = 'employeeCreate',
  ROLE_CREATE = 'roleCreate',
  ROLE_EDIT = 'roleEdit',
  USER_EDIT = 'userEdit',
  EMPLOYEE_EDIT = 'employeeEdit',
  USER_VIEW = 'userView',
  EMPLOYEE_VIEW = 'employeeView',
  CATALOG_CATEGORY_CREATE = 'catalogCategoryCreate',
  CATALOG_CATEGORY_EDIT = 'catalogCategoryEdit',
  CATALOG_ITEM_CREATE = 'catalogItemCreate',
  CATALOG_ITEM_EDIT = 'catalogItemEdit',
  ORGANIZATION_RESTAURANT_CREATE = 'organizationRestaurantCreate',
  ORGANIZATION_RESTAURANT_DETAIL = 'organizationRestaurantDetail',
  ORGANIZATION_RESTAURANT_EDIT = 'organizationRestaurantEdit',
  FLOOR_HALL_CREATE = 'floorHallCreate',
  FLOOR_HALL_EDIT = 'floorHallEdit',
  FLOOR_ZONE_CREATE = 'floorZoneCreate',
  FLOOR_ZONE_EDIT = 'floorZoneEdit',
  FLOOR_TABLE_SESSION_CREATE = 'floorTableSessionCreate',
  FLOOR_TABLE_SESSION_EDIT = 'floorTableSessionEdit',
  NOTFOUND = 'notfound',
}

export const enum AppRoutesRoot {
  AUTH = 'auth',
  MAIN = 'main',
  PRODUCT_OWNER = 'productOwner',
  BUSINESS_PARTNER = 'businessPartner',
  RESTAURANT_ADMIN = 'restaurantAdmin',
  USER_MANAGEMENT = 'userManagement',
  ERROR = 'error',
}

export const RouteRootPath: Record<AppRoutesRoot, string> = {
  [AppRoutesRoot.MAIN]: '/',
  [AppRoutesRoot.AUTH]: '/auth',
  [AppRoutesRoot.PRODUCT_OWNER]: '/product-owner',
  [AppRoutesRoot.BUSINESS_PARTNER]: '/business-partner',
  [AppRoutesRoot.RESTAURANT_ADMIN]: '/restaurant-admin',
  [AppRoutesRoot.USER_MANAGEMENT]: '/user-management',
  [AppRoutesRoot.ERROR]: '/error',
};

const PRODUCT_OWNER_ROOT = RouteRootPath[AppRoutesRoot.PRODUCT_OWNER];
const BUSINESS_PARTNER_ROOT = RouteRootPath[AppRoutesRoot.BUSINESS_PARTNER];
const RESTAURANT_ADMIN_ROOT = RouteRootPath[AppRoutesRoot.RESTAURANT_ADMIN];
const USER_MANAGEMENT_ROOT = RouteRootPath[AppRoutesRoot.USER_MANAGEMENT];

export const RoutePath: Record<AppRoutes, string> = {
  [AppRoutes.LOGIN]: `${RouteRootPath[AppRoutesRoot.AUTH]}/login`,
  [AppRoutes.MAIN]: RouteRootPath[AppRoutesRoot.MAIN],
  [AppRoutes.USER_LIST]: `${USER_MANAGEMENT_ROOT}/users`,
  [AppRoutes.EMPLOYEE_LIST]: `${RESTAURANT_ADMIN_ROOT}/employees`,
  [AppRoutes.ROLE_LIST]: `${USER_MANAGEMENT_ROOT}/roles`,
  [AppRoutes.PERMISSION_LIST]: `${USER_MANAGEMENT_ROOT}/permissions`,
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_LIST]: `${PRODUCT_OWNER_ROOT}/business-partners`,
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_CREATE]: `${PRODUCT_OWNER_ROOT}/business-partners/add`,
  [AppRoutes.PLATFORM_BUSINESS_PARTNER_EDIT]: `${PRODUCT_OWNER_ROOT}/business-partners/:id/edit`,
  [AppRoutes.PLATFORM_TARIFF_LIST]: `${PRODUCT_OWNER_ROOT}/tariffs`,
  [AppRoutes.PLATFORM_TARIFF_CREATE]: `${PRODUCT_OWNER_ROOT}/tariffs/add`,
  [AppRoutes.PLATFORM_TARIFF_EDIT]: `${PRODUCT_OWNER_ROOT}/tariffs/:id/edit`,
  [AppRoutes.ORDER_LIST]: `${RESTAURANT_ADMIN_ROOT}/orders`,
  [AppRoutes.ORDER_VIEW]: `${RESTAURANT_ADMIN_ROOT}/orders/:id`,
  [AppRoutes.ORDER_ITEM_LIST]: `${RESTAURANT_ADMIN_ROOT}/orders/items`,
  [AppRoutes.ORDER_ITEM_VIEW]: `${RESTAURANT_ADMIN_ROOT}/orders/items/:id`,
  [AppRoutes.ORDER_ITEM_NOTE_LIST]: `${RESTAURANT_ADMIN_ROOT}/orders/items/notes`,
  [AppRoutes.ORDER_ITEM_NOTE_VIEW]: `${RESTAURANT_ADMIN_ROOT}/orders/items/notes/:id`,
  [AppRoutes.PAYMENT_LIST]: `${RESTAURANT_ADMIN_ROOT}/orders/payments`,
  [AppRoutes.PAYMENT_VIEW]: `${RESTAURANT_ADMIN_ROOT}/orders/payments/:id`,
  [AppRoutes.RECEIPT_LIST]: `${RESTAURANT_ADMIN_ROOT}/orders/receipts`,
  [AppRoutes.RECEIPT_VIEW]: `${RESTAURANT_ADMIN_ROOT}/orders/receipts/:id`,
  [AppRoutes.REPORTS]: `${RESTAURANT_ADMIN_ROOT}/reports`,
  [AppRoutes.REPORT_DETAIL]: `${RESTAURANT_ADMIN_ROOT}/reports/:reportKey`,
  [AppRoutes.KITCHEN_TICKET_LIST]: `${RESTAURANT_ADMIN_ROOT}/kitchen/tickets`,
  [AppRoutes.KITCHEN_TICKET_VIEW]: `${RESTAURANT_ADMIN_ROOT}/kitchen/tickets/:id`,
  [AppRoutes.CATALOG_CATEGORY_LIST]: `${RESTAURANT_ADMIN_ROOT}/catalog/categories`,
  [AppRoutes.CATALOG_BROWSER]: `${RESTAURANT_ADMIN_ROOT}/catalog/browser`,
  [AppRoutes.CATALOG_ITEM_LIST]: `${RESTAURANT_ADMIN_ROOT}/catalog/items`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT_GENERAL]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management/general`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT_CASH_DESK_LIST]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management/cash-desks`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT_PREP_STATION_LIST]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management/prep-stations`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT_DISTRIBUTION_POINT_LIST]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management/distribution-points`,
  [AppRoutes.ORGANIZATION_MY_RESTAURANT_INTEGRATION_CONFIG_LIST]: `${RESTAURANT_ADMIN_ROOT}/restaurant-management/integrations`,
  [AppRoutes.ORGANIZATION_RESTAURANT_LIST]: `${BUSINESS_PARTNER_ROOT}/restaurants`,
  [AppRoutes.FLOOR_HALL_LIST]: `${RESTAURANT_ADMIN_ROOT}/floor/halls`,
  [AppRoutes.FLOOR_HALL_CONSTRUCTOR]: `${RESTAURANT_ADMIN_ROOT}/floor/halls/:id/constructor`,
  [AppRoutes.FLOOR_ZONE_LIST]: `${RESTAURANT_ADMIN_ROOT}/floor/zones`,
  [AppRoutes.FLOOR_TABLE_SESSION_LIST]: `${RESTAURANT_ADMIN_ROOT}/floor/table-sessions`,
  [AppRoutes.USER_CREATE]: `${USER_MANAGEMENT_ROOT}/users/add`,
  [AppRoutes.EMPLOYEE_CREATE]: `${RESTAURANT_ADMIN_ROOT}/employees/add`,
  [AppRoutes.ROLE_CREATE]: `${USER_MANAGEMENT_ROOT}/roles/add`,
  [AppRoutes.ROLE_EDIT]: `${USER_MANAGEMENT_ROOT}/roles/:id/edit`,
  [AppRoutes.USER_EDIT]: `${USER_MANAGEMENT_ROOT}/users/:id/edit`,
  [AppRoutes.EMPLOYEE_EDIT]: `${RESTAURANT_ADMIN_ROOT}/employees/:id/edit`,
  [AppRoutes.USER_VIEW]: `${USER_MANAGEMENT_ROOT}/users/:id`,
  [AppRoutes.EMPLOYEE_VIEW]: `${RESTAURANT_ADMIN_ROOT}/employees/:id`,
  [AppRoutes.CATALOG_CATEGORY_CREATE]: `${RESTAURANT_ADMIN_ROOT}/catalog/categories/add`,
  [AppRoutes.CATALOG_CATEGORY_EDIT]: `${RESTAURANT_ADMIN_ROOT}/catalog/categories/:id/edit`,
  [AppRoutes.CATALOG_ITEM_CREATE]: `${RESTAURANT_ADMIN_ROOT}/catalog/items/add`,
  [AppRoutes.CATALOG_ITEM_EDIT]: `${RESTAURANT_ADMIN_ROOT}/catalog/items/:id/edit`,
  [AppRoutes.ORGANIZATION_RESTAURANT_CREATE]: `${BUSINESS_PARTNER_ROOT}/restaurants/add`,
  [AppRoutes.ORGANIZATION_RESTAURANT_DETAIL]: `${BUSINESS_PARTNER_ROOT}/restaurants/:id`,
  [AppRoutes.ORGANIZATION_RESTAURANT_EDIT]: `${BUSINESS_PARTNER_ROOT}/restaurants/:id/edit`,
  [AppRoutes.FLOOR_HALL_CREATE]: `${RESTAURANT_ADMIN_ROOT}/floor/halls/add`,
  [AppRoutes.FLOOR_HALL_EDIT]: `${RESTAURANT_ADMIN_ROOT}/floor/halls/:id/edit`,
  [AppRoutes.FLOOR_ZONE_CREATE]: `${RESTAURANT_ADMIN_ROOT}/floor/zones/add`,
  [AppRoutes.FLOOR_ZONE_EDIT]: `${RESTAURANT_ADMIN_ROOT}/floor/zones/:id/edit`,
  [AppRoutes.FLOOR_TABLE_SESSION_CREATE]: `${RESTAURANT_ADMIN_ROOT}/floor/table-sessions/add`,
  [AppRoutes.FLOOR_TABLE_SESSION_EDIT]: `${RESTAURANT_ADMIN_ROOT}/floor/table-sessions/:id/edit`,
  [AppRoutes.NOTFOUND]: RouteRootPath[AppRoutesRoot.ERROR],
} as const;

export const RouterPathHelper = {
  platformBusinessPartnerEdit: (id: string) => getPath(AppRoutes.PLATFORM_BUSINESS_PARTNER_EDIT, { id }),
  platformTariffEdit: (id: string) => getPath(AppRoutes.PLATFORM_TARIFF_EDIT, { id }),
  userView: (id: string) => getPath(AppRoutes.USER_VIEW, { id }),
  employeeView: (id: string) => getPath(AppRoutes.EMPLOYEE_VIEW, { id }),
  orderView: (id: string) => getPath(AppRoutes.ORDER_VIEW, { id }),
  orderItemView: (id: string) => getPath(AppRoutes.ORDER_ITEM_VIEW, { id }),
  orderItemNoteView: (id: string) => getPath(AppRoutes.ORDER_ITEM_NOTE_VIEW, { id }),
  paymentView: (id: string) => getPath(AppRoutes.PAYMENT_VIEW, { id }),
  receiptView: (id: string) => getPath(AppRoutes.RECEIPT_VIEW, { id }),
  reportDetail: (reportKey: string) => getPath(AppRoutes.REPORT_DETAIL, { reportKey }),
  kitchenTicketView: (id: string) => getPath(AppRoutes.KITCHEN_TICKET_VIEW, { id }),
  userEdit: (id: string) => getPath(AppRoutes.USER_EDIT, { id }),
  employeeEdit: (id: string) => getPath(AppRoutes.EMPLOYEE_EDIT, { id }),
  roleEdit: (id: string) => getPath(AppRoutes.ROLE_EDIT, { id }),
  catalogCategoryEdit: (id: string) => getPath(AppRoutes.CATALOG_CATEGORY_EDIT, { id }),
  catalogItemEdit: (id: string) => getPath(AppRoutes.CATALOG_ITEM_EDIT, { id }),
  organizationRestaurantDetail: (id: string) => getPath(AppRoutes.ORGANIZATION_RESTAURANT_DETAIL, { id }),
  organizationRestaurantEdit: (id: string) => getPath(AppRoutes.ORGANIZATION_RESTAURANT_EDIT, { id }),
  floorHallEdit: (id: string) => getPath(AppRoutes.FLOOR_HALL_EDIT, { id }),
  floorHallConstructor: (id: string) => getPath(AppRoutes.FLOOR_HALL_CONSTRUCTOR, { id }),
  floorZoneEdit: (id: string) => getPath(AppRoutes.FLOOR_ZONE_EDIT, { id }),
  floorTableSessionEdit: (id: string) => getPath(AppRoutes.FLOOR_TABLE_SESSION_EDIT, { id }),
} as const;
